export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_ERROR = 'AUTH_LOGIN_ERROR';

export const AUTH_GET_USER_REQUEST = 'AUTH_GET_USER_REQUEST';
export const AUTH_GET_USER_SUCCESS = 'AUTH_GET_USER_SUCCESS';
export const AUTH_GET_USER_ERROR = 'AUTH_GET_USER_ERROR';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const AUTH_REGISTRATION_REQUEST = 'AUTH_REGISTRATION_REQUEST';
export const AUTH_REGISTRATION_SUCCESS = 'AUTH_REGISTRATION_SUCCESS';
export const AUTH_REGISTRATION_ERROR = 'AUTH_REGISTRATION_ERROR';

export const AUTH_FORGOT_PASSWORD_REQUEST = 'AUTH_FORGOT_PASSWORD_REQUEST';
export const AUTH_FORGOT_PASSWORD_SUCCESS = 'AUTH_FORGOT_PASSWORD_SUCCESS';
export const AUTH_FORGOT_PASSWORD_ERROR = 'AUTH_FORGOT_PASSWORD_ERROR';

export const AUTH_RESET_PASSWORD_REQUEST = 'AUTH_RESET_PASSWORD_REQUEST';
export const AUTH_RESET_PASSWORD_SUCCESS = 'AUTH_RESET_PASSWORD_SUCCESS';
export const AUTH_RESET_PASSWORD_ERROR = 'AUTH_RESET_PASSWORD_ERROR';

export const AUTH_CONFIRM_EMAIL_REQUEST = 'AUTH_CONFIRM_EMAIL_REQUEST';
export const AUTH_CONFIRM_EMAIL_SUCCESS = 'AUTH_CONFIRM_EMAIL_SUCCESS';
export const AUTH_CONFIRM_EMAIL_ERROR = 'AUTH_CONFIRM_EMAIL_ERROR';

export const AUTH_CHANGE_STEP_REGISTRATION = 'AUTH_CHANGE_STEP_REGISTRATION';
