export const PLAYERS_GET_PLAYERS_REQUEST = 'PLAYERS_GET_PLAYERS_REQUEST';
export const PLAYERS_GET_PLAYERS = 'PLAYERS_GET_PLAYERS';
export const PLAYERS_GET_PLAYERS_SUCCESS = 'PLAYERS_GET_PLAYERS_REQUEST';
export const PLAYERS_GET_PLAYERS_ERROR = 'PLAYERS_GET_PLAYERS_ERROR';
