export const TOURNAMENTS_GET_TOURNAMENTS = 'TOURNAMENTS_GET_TOURNAMENTS';
export const TOURNAMENTS_GET_SUCCESS = 'TOURNAMENTS_GET_SUCCESS';
export const TOURNAMENTS_GET_ERROR = 'TOURNAMENTS_GET_ERROR';

export const TOURNAMENTS_GET_CURRENT = 'TOURNAMENTS_GET_CURRENT';
export const TOURNAMENTS_GET_CURRENT_SUCCESS = 'TOURNAMENTS_GET_CURRENT_SUCCESS';
export const TOURNAMENTS_GET_CURRENT_ERROR = 'TOURNAMENTS_GET_CURRENT_ERROR';
